# Generated by Django 3.2.5 on 2022-09-06 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_change',
            field=models.DateField(auto_now=True, verbose_name='Дата и время изменения игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания игры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='date_change',
            field=models.DateField(auto_now=True, verbose_name='Дата и время изменения профиля'),
        ),
        migrations.AddField(
            model_name='player',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания профиля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=54, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', help_text='Пожалуйста используйте только буквы a-f и цифры 0-9', max_length=54, unique=True, verbose_name='Имя игрока'),
        ),
    ]
