# Generated by Django 3.2.5 on 2022-09-06 13:34

import callback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_auto_20220906_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=254, unique=True, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения профиля'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', help_text='Пожалуйста используйте только буквы a-f и цифры 0-9', max_length=54, unique=True, validators=[callback.models.validate_name], verbose_name='Имя игрока'),
        ),
    ]
